version: "3.7"

services:
  web:
    image: acdemeg/web-downloader:${TAG}
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    working_dir: /server
    command: "java -jar WebDownloader.jar"
    volumes:
      - ~/web-downloader-data/logs:/server/logs
      - ~/web-downloader-data/registry:/root/web-downloader-data/registry
    ports:
      - "8080:8080"
