server:
  port: 8080
spring:
  main:
    web-application-type: servlet

management:
  endpoints:
    web:
      exposure:
        include: '*'
  http exchanges:
    recording:
      include: RESPONSE_HEADERS
